name: Upload to S3
on: push

jobs:
  upload:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master  
      - name: Upload file to bucket
        with: 
          id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY}}
          aws_bucket: myabhi-bucket
          source_dir: 'sub'
